spring:
  datasource:
    url: jdbc:mysql://db.leoli.wiki:3306/exception_handler?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: leoli
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level: debug
  file:
    name: deplog-debug.log
    path: ../logs