server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://db.leoli.wiki:3306/exception_handler?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: leoli
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    leoli: debug
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
  file:
    name: ../logs/deploy-debug.log