server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://db.leoli.wiki:3306/leoli-app-deploy?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: leoli
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enable: true #开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

logging:
  level:
    leoli: debug
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
  file:
    name: ../logs/deploy-debug.log