server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db.leoli.wiki:3306/exception_handler?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: leoli
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    leoli: debug
  file:
    name: ../logs/deploy-debug.log